### ISSUE TITLE
login problems

### ISSUE THREAD

**Issue by peter-mouland** [shawnrice/gh-scrum-board#28]
hey - I was interested in how far you have got with this idea, sounds interesting.

unfortunately i couldn't view any repos : 

```
 https://api.github.com/repos/shawnrice/gh-scrum-board 401 (Unauthorized)


"{↵  "message": "Bad credentials",↵  "documentation_url": "https://developer.github.com/v3"↵}
```

or login

```
https://api.github.com/ 401 (Unauthorized)
```

is this ready for demo or am i a bit early?

**Comment by shawnrice** [comment]
It was something that I whipped up as a proof of concept about a year ago. The login used to work, but it must have stopped at some point. I had to change my GH to 2fa, which means using personal access tokens as passwords, so I always assumed it was that. But GH might have changed their authentication protocol since then.
